#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running lint-staged"
npm run --prefix ./services/gateway lintStaged
npm run --prefix ./services/users lintStaged
echo "Running tsc"
npm run --prefix ./services/gateway listErrors
npm run --prefix ./services/users listErrors
echo "Running unit tests"
npm run --prefix ./services/gateway test:unit
npm run --prefix ./services/users test:unit
echo "Running database tests"
npm run --prefix ./services/users test:db
npm run --prefix ./services/users test:db